spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:hodolog
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true

hodolman:
  jwt-key: "e4c4bpT90UfRmmnmlS2Qt9p/O8VU2Xk2NKxVOeRNMVI="
