### 로그인
POST http://localhost:8080/auth/login
Content-Type: application/x-www-form-urlencoded

username=hodolman&password=1234&remember=1

### 인증 페이지 요청
GET http://localhost:8080/foo
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjgyNDAzMDU0fQ.U1y6mCbkC3f_uA33pBBpQX8zRfhzrt9nKLgrVf5WDVo

### 메인 페이지 요청
GET http://localhost:8080/
