### 로그인
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email" : "hodoman88@gmail.com",
  "password": "1234"
}

### 인증 페이지 요청
GET http://localhost:8080/foo
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIn0.-i7lmMr_VF6wWZuuHRL1Zv7vJ9gpfnXvvY0wfvVOw48